### ISSUE TITLE
sliders for confidence intervals

### ISSUE THREAD

**Issue by patrickkwang** [patrickkwang/cruncher#14]
for example, iCDF(0.05) to iCDF(0.95) -> [a,b]

**Comment by txje** [comment]
I don't understand what you want. Is this one slider with two points on it to define a range under which we want to compute the iCDF, or two or more different sliders?

**Comment by patrickkwang** [comment]
Two points, one slider. It would also be super neat if we could tie the two sliders together such that the user can move either one, but the other stays the same distance from 0.5 (e.g. 0.05 and 0.95, or 0.2 and 0.8, but not 0.2 and 0.95, because that would be a ridiculous confidence interval). The iCDF is computed for both points, e.g. a 90% (0.05/0.95) confidence interval could be [1,11] if the mean is 6.

**Comment by txje** [comment]
1db49cb
