### ISSUE TITLE
text bbox is of size zero at initialization

### ISSUE THREAD

**Issue by patrickkwang** [patrickkwang/cruncher#15]
remove d3 from histogram stuff first, then hopefully the solution will be clearer

**Comment by patrickkwang** [comment]
I've been unable to correct this issue. @txje could you take a look at b41bdb459702bf4c5f10419e4e60122678b38c64, dataset.js, line 319/337/340?

**Comment by txje** [comment]
8807131

Probably my bad - the trick with zeroed BBoxes is the element was never actually rendered. This was because the dataset tab was not displayed immediately be default. Fixed it.
