### ISSUE TITLE
dual slider weirdness

### ISSUE THREAD

**Issue by patrickkwang** [patrickkwang/cruncher#17]
<img width="227" alt="screen shot 2016-06-25 at 10 13 49 am" src="https://cloud.githubusercontent.com/assets/1263870/16357210/b1b76dbc-3abd-11e6-9428-9c64b5ecaeab.png">
These values sum to 1 most of the time, but weird states like this are not hard to get into.

**Comment by txje** [comment]
It's rounding

**Comment by patrickkwang** [comment]
Per offline convo, rounding is very tricky. Bypass this issue by ensuring that the normalized slider positions have more than 3 decimal places. This is easily accomplished by making the slider width 201 rather than 200 (slider positions are integers).

e8a3783f3e4c7010153ff760bb384806aa47a5dd

**Comment by txje** [comment]
caaaf68
